services:
  starflix:
    build: .
    volumes:
      - .:/usr/src/starflix
      - /usr/src/starflix/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - starflix-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: starflix
    ports:
      - "5432:5432"
    networks:
      - starflix-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  starflix-network:
    driver: bridge